language: python
python: "3.6"
install:
 - pip install dnspython
script:
 - python walk_dotsk_ds.py
deploy:
 provider: script
 skip_cleanup: true
 script: deploy-gh-pages.sh
 on:
        branch: master
# https://stackoverflow.com/questions/49431680/publish-releases-to-gh-pages-with-travis-without-deleting-previous-releases
